const mockMenu = [
    {
        "item_id": "101",
        "name": "Margherita Pizza",
        "price": 10.99,
        "category": "Pizza",
    },
    {
        "item_id": "102",
        "name": "Pepperoni Pizza",
        "price": 11.99,
        "category": "Pizza",
    },
    {
        "item_id": "103",
        "name": "Hawaiian Pizza",
        "price": 12.50,
        "category": "Pizza",
    },
    {
        "item_id": "104",
        "name": "Meat Lovers Pizza",
        "price": 13.99,
        "category": "Pizza",
    },
    {
        "item_id": "105",
        "name": "Veggie Delight Pizza",
        "price": 12.25,
        "category": "Pizza",
    },
    {
        "item_id": "201",
        "name": "Grilled Chicken Club",
        "price": 9.75,
        "category": "Sandwiches",
    },
    {
        "item_id": "202",
        "name": "B.L.T. Sandwich",
        "price": 8.50,
        "category": "Sandwiches",
    },
    {
        "item_id": "203",
        "name": "Tuna Salad Sandwich",
        "price": 8.99,
        "category": "Sandwiches",
    },
    {
        "item_id": "204",
        "name": "Veggie Burger",
        "price": 9.25,
        "category": "Sandwiches",
    },
    {
        "item_id": "205",
        "name": "Philly Cheesesteak",
        "price": 10.50,
        "category": "Sandwiches",
    },
    {
        "item_id": "301",
        "name": "Caesar Salad",
        "price": 8.25,
        "category": "Salads",
    },
    {
        "item_id": "302",
        "name": "Greek Salad",
        "price": 7.75,
        "category": "Salads",
    },
    {
        "item_id": "303",
        "name": "Chopped Salad",
        "price": 9.00,
        "category": "Salads",
    },
    {
        "item_id": "304",
        "name": "Southwest Chicken Salad",
        "price": 10.25,
        "category": "Salads",
    },
    {
        "item_id": "305",
        "name": "Cobb Salad",
        "price": 9.50,
        "category": "Salads",
    },
    {
        "item_id": "401",
        "name": "Soft Drinks",
        "price": 2.50,
        "category": "Drinks",
    },
    {
        "item_id": "402",
        "name": "Iced Tea",
        "price": 2.75,
        "category": "Drinks",
    },
    {
        "item_id": "403",
        "name": "Freshly Squeezed Orange Juice",
        "price": 3.75,
        "category": "Drinks",
    },
    {
        "item_id": "404",
        "name": "Lemonade",
        "price": 2.75,
        "category": "Drinks",
    },
    {
        "item_id": "405",
        "name": "Coffee",
        "price": 2.00,
        "category": "Drinks",
    },
    {
        "item_id": "501",
        "name": "Chocolate Cake",
        "price": 5.00,
        "category": "Desserts",
    },
    {
        "item_id": "502",
        "name": "Cheesecake",
        "price": 5.50,
        "category": "Desserts",
    },
    {
        "item_id": "503",
        "name": "Apple Pie",
        "price": 4.75,
        "category": "Desserts",
    }
]